services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BackendApi__BaseUrl=http://host.docker.internal:5095
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default


networks:
  default:
